name: yew-tailwindcss
on:
  push:
    branches:
      - main
    paths:
      - 'crates/yew-tailwindcss/**'
      - '.github/workflows/yew-tailwindcss.yml'
jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: crates/yew-tailwindcss
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn --cwd styles install
      - name: Build Css
        run: yarn --cwd styles build
      - uses: Swatinem/rust-cache@v1
      - name: Install Wasmpack
        run: cargo install wasm-pack
      - name: Build
        run: wasm-pack build --target web --out-name wasm --out-dir ./dist
      - name: Upload Static Files
        uses: actions/upload-artifact@v2
        with:
          name: yew-tailwindcss
          path: /home/runner/work/rustbyexample/rustbyexample/crates/yew-tailwindcss/dist
  publish:
    runs-on: ubuntu-20.04
    needs: [build]
    env:
      TCB_API_KEY_ID: ${{ secrets.TCB_API_KEY_ID }}
      TCB_API_KEY: ${{ secrets.TCB_API_KEY }}
      TCB_ENV_ID: ${{ secrets.YEW_TAILWINDCSS_ENV_ID }}
    steps:
      - uses: actions/setup-node@v1
      - name: Download Static Files
        uses: actions/download-artifact@v2
        with:
          name: yew-tailwindcss
          path: dist
      - name: TCB install
        run: yarn global add @cloudbase/cli
      - name: TCB login
        run: $(yarn global bin)/tcb login --apiKeyId $TCB_API_KEY_ID --apiKey $TCB_API_KEY
      - name: TCB clean
        run: |
          yes | $(yarn global bin)/tcb hosting delete -e $TCB_ENV_ID
      - name: TCB publish
        run: $(yarn global bin)/tcb hosting deploy -e $TCB_ENV_ID dist